### ISSUE TITLE
ModuleNotFoundError: No module named 'mmcv._ext'

### ISSUE THREAD

**Issue by PacificHongyang** [LeapLabTHU/Agent-Attention#21]
/home/algorithms/Agent-Attention/downstream/mmcv/mmcv/cnn/bricks/transformer.py:33: UserWarning: Fail to import ``MultiScaleDeformableAttention`` from ``mmcv.ops.multi_scale_deform_attn``, You should install ``mmcv-full`` if you need this module.
  warnings.warn('Fail to import ``MultiScaleDeformableAttention`` from '
Traceback (most recent call last):
  File "tools/test.py", line 17, in <module>
    from mmseg.apis import multi_gpu_test, single_gpu_test
  File "/home/algorithms/Agent-Attention/downstream/segmentation/mmseg/apis/__init__.py", line 2, in <module>
    from .inference import inference_segmentor, init_segmentor, show_result_pyplot
  File "/home/algorithms/Agent-Attention/downstream/segmentation/mmseg/apis/inference.py", line 9, in <module>
    from mmseg.models import build_segmentor
  File "/home/algorithms/Agent-Attention/downstream/segmentation/mmseg/models/__init__.py", line 2, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/home/algorithms/Agent-Attention/downstream/segmentation/mmseg/models/backbones/__init__.py", line 7, in <module>
    from .fast_scnn import FastSCNN
  File "/home/algorithms/Agent-Attention/downstream/segmentation/mmseg/models/backbones/fast_scnn.py", line 7, in <module>
    from mmseg.models.decode_heads.psp_head import PPM
  File "/home/algorithms/Agent-Attention/downstream/segmentation/mmseg/models/decode_heads/__init__.py", line 2, in <module>
    from .ann_head import ANNHead
  File "/home/algorithms/Agent-Attention/downstream/segmentation/mmseg/models/decode_heads/ann_head.py", line 8, in <module>
    from .decode_head import BaseDecodeHead
  File "/home/algorithms/Agent-Attention/downstream/segmentation/mmseg/models/decode_heads/decode_head.py", line 12, in <module>
    from ..losses import accuracy
  File "/home/algorithms/Agent-Attention/downstream/segmentation/mmseg/models/losses/__init__.py", line 6, in <module>
    from .focal_loss import FocalLoss
  File "/home/algorithms/Agent-Attention/downstream/segmentation/mmseg/models/losses/focal_loss.py", line 6, in <module>
    from mmcv.ops import sigmoid_focal_loss as _sigmoid_focal_loss
  File "/home/algorithms/Agent-Attention/downstream/mmcv/mmcv/ops/__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "/home/algorithms/Agent-Attention/downstream/mmcv/mmcv/ops/active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "/home/algorithms/Agent-Attention/downstream/mmcv/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/root/miniconda3/envs/agent_segmentation/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmcv._ext'

**Comment by YTianZHU** [comment]
Hi! Please follow the installation guide here: 
https://github.com/LeapLabTHU/Agent-Attention/tree/master/downstream/detection#installation
to solve the problem.
